//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eload
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EloadEntities : DbContext
    {
        public EloadEntities()
            : base("name=EloadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_Operator> TB_Operator { get; set; }
        public DbSet<TB_Product> TB_Product { get; set; }
        public DbSet<TB_Transaction> TB_Transaction { get; set; }
        public DbSet<TB_User> TB_User { get; set; }
    }
}
