//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EloadModel", "FK_TB_Product_TB_Operator", "TB_Operator", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Eload.TB_Operator), "TB_Product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Eload.TB_Product), true)]
[assembly: EdmRelationshipAttribute("EloadModel", "FK_TB_Transaction_TB_Product", "TB_Product", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Eload.TB_Product), "TB_Transaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Eload.TB_Transaction), true)]
[assembly: EdmRelationshipAttribute("EloadModel", "FK_TB_Transaction_TB_User", "TB_User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Eload.TB_User), "TB_Transaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Eload.TB_Transaction), true)]

#endregion

namespace Eload
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EloadEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EloadEntities object using the connection string found in the 'EloadEntities' section of the application configuration file.
        /// </summary>
        public EloadEntities() : base("name=EloadEntities", "EloadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EloadEntities object.
        /// </summary>
        public EloadEntities(string connectionString) : base(connectionString, "EloadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EloadEntities object.
        /// </summary>
        public EloadEntities(EntityConnection connection) : base(connection, "EloadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_Operator> TB_Operator
        {
            get
            {
                if ((_TB_Operator == null))
                {
                    _TB_Operator = base.CreateObjectSet<TB_Operator>("TB_Operator");
                }
                return _TB_Operator;
            }
        }
        private ObjectSet<TB_Operator> _TB_Operator;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_Product> TB_Product
        {
            get
            {
                if ((_TB_Product == null))
                {
                    _TB_Product = base.CreateObjectSet<TB_Product>("TB_Product");
                }
                return _TB_Product;
            }
        }
        private ObjectSet<TB_Product> _TB_Product;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_Transaction> TB_Transaction
        {
            get
            {
                if ((_TB_Transaction == null))
                {
                    _TB_Transaction = base.CreateObjectSet<TB_Transaction>("TB_Transaction");
                }
                return _TB_Transaction;
            }
        }
        private ObjectSet<TB_Transaction> _TB_Transaction;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_User> TB_User
        {
            get
            {
                if ((_TB_User == null))
                {
                    _TB_User = base.CreateObjectSet<TB_User>("TB_User");
                }
                return _TB_User;
            }
        }
        private ObjectSet<TB_User> _TB_User;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_Operator EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_Operator(TB_Operator tB_Operator)
        {
            base.AddObject("TB_Operator", tB_Operator);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_Product EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_Product(TB_Product tB_Product)
        {
            base.AddObject("TB_Product", tB_Product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_Transaction EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_Transaction(TB_Transaction tB_Transaction)
        {
            base.AddObject("TB_Transaction", tB_Transaction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_User(TB_User tB_User)
        {
            base.AddObject("TB_User", tB_User);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EloadModel", Name="TB_Operator")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_Operator : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_Operator object.
        /// </summary>
        /// <param name="operatorId">Initial value of the OperatorId property.</param>
        public static TB_Operator CreateTB_Operator(global::System.Int32 operatorId)
        {
            TB_Operator tB_Operator = new TB_Operator();
            tB_Operator.OperatorId = operatorId;
            return tB_Operator;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OperatorId
        {
            get
            {
                return _OperatorId;
            }
            set
            {
                if (_OperatorId != value)
                {
                    OnOperatorIdChanging(value);
                    ReportPropertyChanging("OperatorId");
                    _OperatorId = StructuralObject.SetValidValue(value, "OperatorId");
                    ReportPropertyChanged("OperatorId");
                    OnOperatorIdChanged();
                }
            }
        }
        private global::System.Int32 _OperatorId;
        partial void OnOperatorIdChanging(global::System.Int32 value);
        partial void OnOperatorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OperatorName
        {
            get
            {
                return _OperatorName;
            }
            set
            {
                OnOperatorNameChanging(value);
                ReportPropertyChanging("OperatorName");
                _OperatorName = StructuralObject.SetValidValue(value, true, "OperatorName");
                ReportPropertyChanged("OperatorName");
                OnOperatorNameChanged();
            }
        }
        private global::System.String _OperatorName;
        partial void OnOperatorNameChanging(global::System.String value);
        partial void OnOperatorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true, "Country");
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EloadModel", "FK_TB_Product_TB_Operator", "TB_Product")]
        public EntityCollection<TB_Product> TB_Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_Product>("EloadModel.FK_TB_Product_TB_Operator", "TB_Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_Product>("EloadModel.FK_TB_Product_TB_Operator", "TB_Product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EloadModel", Name="TB_Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_Product object.
        /// </summary>
        /// <param name="tB_ProductID">Initial value of the TB_ProductID property.</param>
        public static TB_Product CreateTB_Product(global::System.Int32 tB_ProductID)
        {
            TB_Product tB_Product = new TB_Product();
            tB_Product.TB_ProductID = tB_ProductID;
            return tB_Product;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TB_ProductID
        {
            get
            {
                return _TB_ProductID;
            }
            set
            {
                if (_TB_ProductID != value)
                {
                    OnTB_ProductIDChanging(value);
                    ReportPropertyChanging("TB_ProductID");
                    _TB_ProductID = StructuralObject.SetValidValue(value, "TB_ProductID");
                    ReportPropertyChanged("TB_ProductID");
                    OnTB_ProductIDChanged();
                }
            }
        }
        private global::System.Int32 _TB_ProductID;
        partial void OnTB_ProductIDChanging(global::System.Int32 value);
        partial void OnTB_ProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value, "ProductId");
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProductId;
        partial void OnProductIdChanging(Nullable<global::System.Int32> value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Product_Price
        {
            get
            {
                return _Product_Price;
            }
            set
            {
                OnProduct_PriceChanging(value);
                ReportPropertyChanging("Product_Price");
                _Product_Price = StructuralObject.SetValidValue(value, "Product_Price");
                ReportPropertyChanged("Product_Price");
                OnProduct_PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Product_Price;
        partial void OnProduct_PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnProduct_PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product_Name
        {
            get
            {
                return _Product_Name;
            }
            set
            {
                OnProduct_NameChanging(value);
                ReportPropertyChanging("Product_Name");
                _Product_Name = StructuralObject.SetValidValue(value, true, "Product_Name");
                ReportPropertyChanged("Product_Name");
                OnProduct_NameChanged();
            }
        }
        private global::System.String _Product_Name;
        partial void OnProduct_NameChanging(global::System.String value);
        partial void OnProduct_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OperatorId
        {
            get
            {
                return _OperatorId;
            }
            set
            {
                OnOperatorIdChanging(value);
                ReportPropertyChanging("OperatorId");
                _OperatorId = StructuralObject.SetValidValue(value, "OperatorId");
                ReportPropertyChanged("OperatorId");
                OnOperatorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _OperatorId;
        partial void OnOperatorIdChanging(Nullable<global::System.Int32> value);
        partial void OnOperatorIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EloadModel", "FK_TB_Product_TB_Operator", "TB_Operator")]
        public TB_Operator TB_Operator
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_Operator>("EloadModel.FK_TB_Product_TB_Operator", "TB_Operator").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_Operator>("EloadModel.FK_TB_Product_TB_Operator", "TB_Operator").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_Operator> TB_OperatorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_Operator>("EloadModel.FK_TB_Product_TB_Operator", "TB_Operator");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_Operator>("EloadModel.FK_TB_Product_TB_Operator", "TB_Operator", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EloadModel", "FK_TB_Transaction_TB_Product", "TB_Transaction")]
        public EntityCollection<TB_Transaction> TB_Transaction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_Transaction>("EloadModel.FK_TB_Transaction_TB_Product", "TB_Transaction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_Transaction>("EloadModel.FK_TB_Transaction_TB_Product", "TB_Transaction", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EloadModel", Name="TB_Transaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_Transaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_Transaction object.
        /// </summary>
        /// <param name="transactionId">Initial value of the TransactionId property.</param>
        public static TB_Transaction CreateTB_Transaction(global::System.Int32 transactionId)
        {
            TB_Transaction tB_Transaction = new TB_Transaction();
            tB_Transaction.TransactionId = transactionId;
            return tB_Transaction;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransactionId
        {
            get
            {
                return _TransactionId;
            }
            set
            {
                if (_TransactionId != value)
                {
                    OnTransactionIdChanging(value);
                    ReportPropertyChanging("TransactionId");
                    _TransactionId = StructuralObject.SetValidValue(value, "TransactionId");
                    ReportPropertyChanged("TransactionId");
                    OnTransactionIdChanged();
                }
            }
        }
        private global::System.Int32 _TransactionId;
        partial void OnTransactionIdChanging(global::System.Int32 value);
        partial void OnTransactionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TransactionNumber
        {
            get
            {
                return _TransactionNumber;
            }
            set
            {
                OnTransactionNumberChanging(value);
                ReportPropertyChanging("TransactionNumber");
                _TransactionNumber = StructuralObject.SetValidValue(value, true, "TransactionNumber");
                ReportPropertyChanged("TransactionNumber");
                OnTransactionNumberChanged();
            }
        }
        private global::System.String _TransactionNumber;
        partial void OnTransactionNumberChanging(global::System.String value);
        partial void OnTransactionNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value, "ProductId");
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProductId;
        partial void OnProductIdChanging(Nullable<global::System.Int32> value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Denomination
        {
            get
            {
                return _Denomination;
            }
            set
            {
                OnDenominationChanging(value);
                ReportPropertyChanging("Denomination");
                _Denomination = StructuralObject.SetValidValue(value, true, "Denomination");
                ReportPropertyChanged("Denomination");
                OnDenominationChanged();
            }
        }
        private global::System.String _Denomination;
        partial void OnDenominationChanging(global::System.String value);
        partial void OnDenominationChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EloadModel", "FK_TB_Transaction_TB_Product", "TB_Product")]
        public TB_Product TB_Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_Product>("EloadModel.FK_TB_Transaction_TB_Product", "TB_Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_Product>("EloadModel.FK_TB_Transaction_TB_Product", "TB_Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_Product> TB_ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_Product>("EloadModel.FK_TB_Transaction_TB_Product", "TB_Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_Product>("EloadModel.FK_TB_Transaction_TB_Product", "TB_Product", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EloadModel", "FK_TB_Transaction_TB_User", "TB_User")]
        public TB_User TB_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_User>("EloadModel.FK_TB_Transaction_TB_User", "TB_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_User>("EloadModel.FK_TB_Transaction_TB_User", "TB_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_User> TB_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_User>("EloadModel.FK_TB_Transaction_TB_User", "TB_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_User>("EloadModel.FK_TB_Transaction_TB_User", "TB_User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EloadModel", Name="TB_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static TB_User CreateTB_User(global::System.Int32 userId)
        {
            TB_User tB_User = new TB_User();
            tB_User.UserId = userId;
            return tB_User;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value, true, "Active");
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.String _Active;
        partial void OnActiveChanging(global::System.String value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MobileNumber
        {
            get
            {
                return _MobileNumber;
            }
            set
            {
                OnMobileNumberChanging(value);
                ReportPropertyChanging("MobileNumber");
                _MobileNumber = StructuralObject.SetValidValue(value, true, "MobileNumber");
                ReportPropertyChanged("MobileNumber");
                OnMobileNumberChanged();
            }
        }
        private global::System.String _MobileNumber;
        partial void OnMobileNumberChanging(global::System.String value);
        partial void OnMobileNumberChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EloadModel", "FK_TB_Transaction_TB_User", "TB_Transaction")]
        public EntityCollection<TB_Transaction> TB_Transaction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_Transaction>("EloadModel.FK_TB_Transaction_TB_User", "TB_Transaction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_Transaction>("EloadModel.FK_TB_Transaction_TB_User", "TB_Transaction", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
