//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eload
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Operator
    {
        public TB_Operator()
        {
            this.TB_Product = new HashSet<TB_Product>();
        }
    
        public int OperatorId { get; set; }
        public string OperatorName { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<TB_Product> TB_Product { get; set; }
    }
}
